name: wordstock
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  advanced_in_app_review: ^1.3.0
  animated_flip_counter: ^0.3.4
  audioplayers: ^6.3.0
  bloc: ^8.1.4
  cloud_text_to_speech: ^1.1.3
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.17
  freezed: ^3.0.3
  freezed_annotation: ^3.0.0
  gaimon: ^1.4.0
  go_router: ^14.8.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  image_gallery_saver: ^2.0.3
  in_app_review: ^2.0.10
  intl: ^0.19.0
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  supabase_flutter: ^2.8.4

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
    - assets/secrets/service_account.json
    - .env