name: wordstock
description: A Very Good Project created by Very Good CLI.
version: 1.2.1+25
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  advanced_in_app_review: ^1.3.0
  animated_flip_counter: ^0.3.4
  app_tracking_transparency: ^2.0.4
  audioplayers: ^6.3.0
  bloc: ^8.1.4
  cloud_text_to_speech: ^1.1.3
  connectivity_plus: ^5.0.2
  equatable: ^2.0.7
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^8.1.6
  flutter_branch_sdk: ^8.4.1
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.5
  flutter_svg: ^2.0.17
  flutter_timezone: ^4.1.0
  freezed: ^2.5.8
  freezed_annotation: ^2.0.1
  gaimon: ^1.4.0
  go_router: ^14.8.1
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.0
  image_gallery_saver: ^2.0.3
  in_app_review: ^2.0.10
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  lottie: ^3.3.1
  onesignal_flutter: ^5.3.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  posthog_flutter: ^4.10.8
  purchases_flutter: ^8.7.0
  purchases_ui_flutter: ^8.7.0
  screenshot: ^3.0.0
  sentry_flutter: ^8.14.1
  share_plus: ^10.1.4
  shared_preferences: ^2.5.2
  shimmer: ^3.0.0
  supabase_flutter: ^2.8.4
  url_launcher: ^6.3.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/sounds/
    - assets/secrets/service_account.json
    - .env
